### ISSUE TITLE
Setup voor local development

### ISSUE THREAD

**Issue by tonijn** [noslite/noslite#4]
Hoe krijgen we dit beestje lokaal aan de praat?
Ik krijg de volgende error

`
Uncaught Unavailable: Something wrong with the id in /noslite/src/noslite.php:19
Stack trace:
#0 /noslite/src/noslite.php(53): strip_id('https://nos.nl/...')
#1 /noslite/src/noslite.php(79): parse_feed(Object(SimpleXMLElement))
#2 {main} 
thrown in /noslite/src/noslite.php on line 19
`

**Comment by haampie** [comment]
Was vergeten een fix te pushen blijkbaar; laatste commit in master fixt dit.
